name: continious integration

on:
  pull_request: 
    branches: 
        -main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - run: npm install

      - run: echo "pipeline started at $(date)"

      - name: correction with prettier and eslint
        run: npm run code:fix
      
      - name: jest
        run: npm run test

      - run: echo "PIPELINE SUCESS WITHOUT ERRORS"
      
